# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Facts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facts
  pod 'CollectionManager'
  pod 'ConfigurationProvider'

  target 'FactsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'FactsUITests' do
    
  end

end
