source 'https://github.com/cocoapods/specs.git'
platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'Facts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Facts
  pod 'Alamofire'

  #github myself
  pod 'SelfTableViewManager'

  target 'FactsTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

  target 'FactsUITests' do
    
  end

end
