# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_ios_screenshots(workspace: "Facts.xcworkspace", scheme: "Facts-Debug", reinstall_app: true, erase_simulator: true)
  end

  desc "Runs all the tests"
  lane :tests do
    scan(clean: true, code_coverage: true, scheme: "Facts-Debug", devices: ["iPhone X"])
  end

  desc "Runs Coverage"
  lane :coverage do
   slather(workspace: "Facts.xcworkspace", scheme: "Facts-Debug", html: true, show: true)
  end

end
